import Header from '@/components/Header';
import styles from './Layout.module.css';
import './globals.css';

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return <html lang="en">
        <body className={ styles.body }>
            <Header>
            </Header>
            <main className={ styles.main }>
                {children}
                <h1>Bonjour</h1>
            </main>
            
            
        </body>    
    </html>;
}
